Revert "Allow flags and targets to be specified as sets to allow merging common base configs (#1727)"
Causing https://buildkite.com/bazel/google-bazel-presubmit/builds/70654#018a21e2-7326-4cf2-8cdb-1c809f800142
```
Traceback (most recent call last):
  File "bazelci.py", line 4010, in <module>
    sys.exit(main())
  File "bazelci.py", line 3990, in main
    bazel_version=task_config.get("bazel") or configs.get("bazel"),
  File "bazelci.py", line 1382, in execute_commands
    task_config, "test_flags", "test", tmpdir, test_env_vars
  File "bazelci.py", line 1212, in calculate_flags
    flags = list(task_config.get(task_config_key)) or []
TypeError: 'NoneType' object is not iterable
```

This reverts commit 922e89f3f68cab163febbc210366f4edbca2a910.