Upload test logs with a UTF-8 content type (#2117)
This fixes rendering of test `.log` files when opened in a browser.

Updating the deps was required to get the project to compile due to:
```
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /Users/fmeum/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.56/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^
```

Update command:
```
cargo update proc-macro2 --precise 1.0.60
```